### ISSUE TITLE
Ear points

### ISSUE THREAD

**Issue by jas99** [TadasBaltrusaitis/CLM-framework#12]
@TadasBaltrusaitis Hi I was looking for library to estimate ear location. Does this lib capable of doing it or do you know any other project which has already worked on it?

Thx

**Comment by TadasBaltrusaitis** [comment]
Hi, my framework does not do ear location tracking, and I'm not aware of any that do. You can always try estimating the ear locations based on the face outline points. The points tracked in my framework are as follows:
http://ibug.doc.ic.ac.uk/resources/facial-point-annotations/

**Comment by jas99** [comment]
@TadasBaltrusaitis Hi thx for so quick response :)
I failed to mention I also have depth info along with color. So along with face points also want to estimate ear if not covered up by hair. There is lib PCL which's pretty good for this. I was just looking around the web and asking random intelligent people ;) if there is already work done on this which is open and I am not undertaking redundant tast :)

Jas

**Comment by jas99** [comment]
I deal with 3d depthmap any lib you know for face features annotations with depth only.

Thx

**Comment by TadasBaltrusaitis** [comment]
There is a lot of work on detecting landmarks and head pose using depth images, but I'm not aware of an open source system that does it unfortunately.
