### ISSUE TITLE
Do you have best method to detect eyeglasses with OpenCV

### ISSUE THREAD

**Issue by ming81** [TadasBaltrusaitis/CLM-framework#13]
Do you have best method to detect eyeglasses with OpenCV

**Comment by TadasBaltrusaitis** [comment]
Do you mean detecting if a person is wearing glasses or not? If so I don't, but there might be other face tracking algorithms that do (just not mine).

**Comment by ming81** [comment]
I am looking for a long time did not find the open source code, can you help me?

**Comment by TadasBaltrusaitis** [comment]
I'm not familiar with any open source libraries that do that, but some commercial ones might (like intraface and Emotient FACET).
