### ISSUE TITLE
Difference between SimpleCLMImg and SimpleCLM

### ISSUE THREAD

**Issue by gopi1989** [TadasBaltrusaitis/CLM-framework#14]
Hi Tadas,

I had tried your CLM executables for my work. Really it's an Amazing Algorithm .Once i build your Code i found the executables.I need a clarification whether the SimpleCLMImage and SimpleCLM both are equal in tracking as well as accuracy.
I thought that like this:
SimpleCLM           - for Camera Module
SimpleCLMImage - for Image's

Please clarify my doubt tadas.Thanks in advance for your help!!!!

Regards,
Gopi Krishnan.R

**Comment by TadasBaltrusaitis** [comment]
Hi Gopi,

Glad you found my code useful for your work. SimpleCLMImg and SimpleCLM are slightly different from each other. The former is designed for images (and can handle multiple faces); while the latter is designed for videos (either camera or recorded video file), although it can run on an image, which is then seen as a video of a single frame. The accuracy will differ slightly, especially if you use -clmwild flag with SimpleCLMImg.exe, which will force it to use multiple view hypotheses (which is more accurate for difficult in-the-wild images).

Thanks,
Tadas
