### ISSUE TITLE
How to find the Number of Faces (Detected) in MultiCLM Executables

### ISSUE THREAD

**Issue by gopi1989** [TadasBaltrusaitis/CLM-framework#15]
Hi Tadas,

For ex:
![grouppic](https://cloud.githubusercontent.com/assets/11675678/10949838/f5a69b30-835a-11e5-84df-2b9bf42108d5.jpg)
In the above Image , MultiTrackCLM executable detected all the four faces. How will i get the detected face counts in the MultiTrackCLM.cpp .

In MultiTrackCLM.cpp,I found that num_active_models (Integer Variable). It is correct variable to know the number of faces detected by MultiTrackCLM.cpp.

Regards,
Gopi Krishnan.R

**Comment by TadasBaltrusaitis** [comment]
Hi Gopi,

Are you interested in analysing videos or images? For videos, looking at num_active_models would be the way to do it. For images you could look at SimpleCLMImg project and looking specifically at the face_detections.size() property.

Thanks,
Tadas

**Comment by gopi1989** [comment]
Hi Tadas,

Thank you for your reply!! I got the result everything in a good way..Once again thanks.

Regards,
Gopi
