### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by DraXus** [TadasBaltrusaitis/CLM-framework#16]
Hi! Is there any publication I can cite regarding this software?

**Comment by TadasBaltrusaitis** [comment]
Hi,

There's a number of papers you can cite, depending on what part of the software you were using:

Face tracking using depth images:
Tadas Baltrusaitis, Peter Robinson, and Louis-Philippe Morency. 3D Constrained Local Model for Rigid and Non-Rigid Facial Tracking. CVPR, 2012.    

Face tracking in RGB or grayscale images:
Tadas Baltrusaitis, Peter Robinson, and Louis-Philippe Morency. Constrained Local Neural Fields for robust facial landmark detection in the wild. ICCVW, 300 Faces in-the-Wild Challenge, 2013.    

Facial Action Unit detection:
Tadas Baltrusaitis, Marwa Mahmoud, and Peter Robinson. Cross-dataset learning and person-specific normalisation for automatic Action Unit detection. Facial Expression Recognition and Analysis Challenge 2015, FG 2015

Gaze tracking:
Erroll Wood, Tadas Baltrušaitis, Xucong Zhang, Yusuke Sugano, Peter Robinson, and Andreas Bulling. Rendering of Eyes for Eye-Shape Registration and Gaze Estimation, ICCV, 2015
