### ISSUE TITLE
Windows 8.1 & Visual Studio 2013 Community issue

### ISSUE THREAD

**Issue by ShuaiHuang** [TadasBaltrusaitis/CLM-framework#17]
When I build the `CLM_framework_vs2013.sln` in `VS 2013 Community` & `Windows 8.1` platform, an error occurs as following:

> 1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2012 (Platform Toolset = 'v110') cannot be found. To build using the v110 build tools, please install Visual Studio 2012 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...".

It seems that the `FaceAnalyser_vs2013` has some problems. Morever, I tried to change the project project's `Platform Toolset` property to `Visual Studio (v120)`. But it doesn't work.

Is there anyone can help me on this? Thank you in advance.

**Comment by TadasBaltrusaitis** [comment]
Hi, 

I just made a small change to the project that should fix it (the solution was wrongly including a Visual Studio 2012 rather than 2013 project). Let me know if it works.

-Tadas

**Comment by ShuaiHuang** [comment]
Hi,

I am very glad to receive your reply, and the new version of the project on my computer works well. Thank you for your timely help! Your work is amazing and it is very helpful for me. Thank you again!

**Comment by TadasBaltrusaitis** [comment]
No problem at all, glad that the fix worked and thanks for notifying me about the bug.

-Tadas
