### ISSUE TITLE
what do “fx fy cx cy”mean？

### ISSUE THREAD

**Issue by tabsun** [TadasBaltrusaitis/CLM-framework#22]
I see the arguments input -fx -fy -cx -cy, but I do not know what do these arguments mean? Can anyone give me some explaination?Thank you

**Comment by TadasBaltrusaitis** [comment]
Hi,

They refer to camera calibration parameters (https://en.wikipedia.org/wiki/Camera_resectioning), specifically fx and fy are the focal lengths and cx, cy represent the camera principal point. 

Knowing them accurately is important for head pose estimation, 3D landmark location, and gaze estimation, they do not affect 2D landmark or Action Unit detection. 

If these parameters are not specified the code attempts to get a rough 'guesstimate' based on image size.

Thanks,
Tadas
