### ISSUE TITLE
Add more points to model the eye(s) better

### ISSUE THREAD

**Issue by lydonchandra** [TadasBaltrusaitis/CLM-framework#23]
Hi Tadas,

How can I add more points to model the eye(s) better ?

At the moment, there are only 6 points to track each eye.
Where/how can I add, say, 6 extra points, to make a total of 12 points for each eye?

I got lost reading the source,not sure where to start tinkering.

![screenclip](https://cloud.githubusercontent.com/assets/158145/12007318/be318ad6-ac39-11e5-8e19-e80f10b27d5f.png)

**Comment by TadasBaltrusaitis** [comment]
Hi,

Actually we did some work for better eye region localization and iris tracking, you can find the paper here - http://arxiv.org/abs/1505.05916, and a video description here - https://www.youtube.com/watch?v=q1Jmo5z0K08.

A version of this model is actually included in the FeatureExtractor project/executable, it is used for eye tracking, but the individual landmarks can be accessed.
