### ISSUE TITLE
Usage with no GUI

### ISSUE THREAD

**Issue by khazidhea** [TadasBaltrusaitis/CLM-framework#24]
Hello,

Is it possible to generate face features data by CLM without the GUI?

On Windows when I run SimpleCLMImg.exe it opens up this little window with the images being processed. I successfully compiled CLM on my remote Linux box, but when I try to run it I get:

(colour:12341): Gtk-WARNING **: cannot open display

I guess that's because I don't have any GUI on my Linux box. Is that fixable?

**Comment by TadasBaltrusaitis** [comment]
Hi, 

It is indeed possible to extract features without any vizualisation, you should use -q command line argument to suppress the display.

-Tadas
