### ISSUE TITLE
get distances between two points

### ISSUE THREAD

**Issue by CanGriffel** [TadasBaltrusaitis/CLM-framework#48]
Hey,
the first thing I´ve to say is that I really appreciate your work!

My problem is that I´m trying to detect if the mouth is closed/open and if possible the eyes as well. Thought that I probably take 2 or 4 points and compare the distance but I dont really know which function I should choose to extract these points. I use the FeatureExtraction of the CLM-Frameworkv2012 and my next step would be to check if the eyes look into the camera. 

I already thank you in advance for your help!

**Comment by TadasBaltrusaitis** [comment]
Hi, CLM-Framework is not being maintained anymore, all of the newest changes can be found in OpenFace (https://github.com/TadasBaltrusaitis/OpenFace), it also has a wiki that explains how to use it and extract output from it (https://github.com/TadasBaltrusaitis/OpenFace/wiki)
