### ISSUE TITLE
How to build CLM-framework in Mac OSX.?

### ISSUE THREAD

**Issue by karthikeyanchenniappan** [TadasBaltrusaitis/CLM-framework#5]
I am trying to build CLM-framework in Mac OSX.I got issue when run the CMakelist.txt.

What i did:

1. Builded opencv with TBB

2.run the CmakeLists.txt using CMake GUI.

3. RUN THE COMMAND "make"

I got following issues

`/Users/HubinoMac2/Desktop/CLM-framework-master/exe/MultiTrackCLM/MultiTrackCLM.cpp:325:11: error: 
      use of undeclared identifier 'tbb'
                        vector<tbb::atomic<bool> > face_detections_used(...
                               ^
/Users/HubinoMac2/Desktop/CLM-framework-master/exe/MultiTrackCLM/MultiTrackCLM.cpp:328:4: error: 
      use of undeclared identifier 'tbb'
                        tbb::parallel_for(0, (int)clm_models.size(), [&]...`

How to build CLM-framework in Mac OSX.?

**Comment by TadasBaltrusaitis** [comment]
I don't have a machine with Mac OSX and don't have much experience developing on it. Are you using the gcc compiler and have you installed tbb separately?

**Comment by karthikeyanchenniappan** [comment]
Hi ,
I builded the CLM-framework IN Mac OSX and executed simpleCLM tracker. I builded the CLM-framework for Mobile platform(IOS). But Mobile platform(IOS) did not support TBB .So  I want to build CLM-framework without TBB for Mobile platform.How to build CLM-framework without TBB.?

I tried to set TBB flag:
cmake .. -DWITH_TBB=OFF

But still LibCLM.a need TBB library.

Can you tell how to disable the TBB flag.?

**Comment by TadasBaltrusaitis** [comment]
Hi,

I don't plan on adding support for iOS anytime soon, as I'm not a mobile developer and don't really have a way to test it as well.

One way you could try fixing this is by removing the code that relies on TBB (you would need to convert it back to regular loops though). There are a couple of places where TBB is used in the code (the face detection in dlib), patch expert computation and multiple face tracking (you can just search where tbb is used in the source files).

Thanks,
Tadas

**Comment by karthikeyanchenniappan** [comment]
Thanks for your answer.

 I removed TBB and dlib from this CLM-framework, and I used Haar cascade for face detection instead of Dlib. I got wrong face detection coordinates from CLM face detector code. Is wrong i used for Haar cascade face detection instead of dlib in CLM-framework.?

How to solve this wrong face coordinates from CLM face detection.?

**Comment by TadasBaltrusaitis** [comment]
The Haar face detector is much less reliable, especially in noisy or not well lit environments, but it should still work. You can test if it works by using:

clm_parameters.curr_face_detector = CLMTracker::CLMParameters::HAAR_DETECTOR;

This forces the tracker to use Haar instead of dlib face detector. Alternatively, if the Haar detector is not accurate enough for your purposes you can try using the default dlib code (http://dlib.net/) (as the one included with my tracker was modified to use TBB for speed), however, it will be somewhat slower.

**Comment by karthikeyanchenniappan** [comment]
Thanks for for your reply.

**Comment by karthikeyanchenniappan** [comment]
I tried HAAR_DETECTOR by removing dlib package. But it is run slow in IOS.also I tried another method, dlib package without TBB for IOS. I generated static library of default dlib package. I builded everything for IOS. But i did not get face. Everytime I got face size is Zero. Am i did anything wrong.? can you help me why dlib frontal face detection is nor detect face in IOS.?

**Comment by TadasBaltrusaitis** [comment]
I haven't got experience with running things on IOS so can't really help you. But if HAAR_DETECTOR is too slow for you dlib is very unlikely to be able to run things faster.

Also I'm not the best suited person to ask about dlib face detection issues on IOS, you might have better luck contacting the author of dlib directly.

**Comment by BalajiChinna** [comment]
Thanks for your reply.

**Comment by seemoonseeyou** [comment]
now dou you have CLM for ios?  l really hurry,thanks. thanks..

**Comment by TadasBaltrusaitis** [comment]
For instructions of how to compile for Mac OSX, have a look at:
http://www.learnopencv.com/facial-landmark-detection/?utm_source=tuicool&utm_medium=referral

I do not have a version for use with iOS though and it is not being developed at the moment.

**Comment by seemoonseeyou** [comment]
thanks for your reply.

**Comment by BalajiChinna** [comment]
Yes. I had builded CLM for IOS by modified  DLIB face detection with HAAR detector. Because IOS did not support TBB support. So I remove TBB from DLIB .

**Comment by seemoonseeyou** [comment]
so great, can you send me that lib, i am a student  and l am doing a project, what you said is too difficult for me,and  the deadline is coming,l would be grateful if you could send me a lib,my email is 956513189@qq.com, thanks,thank you very much.-_-||

**Comment by chapayGhub** [comment]
Hi all
I tried to make a port of this library for iOs, but without success ((
Could you please provide tips and instructions how I can do this

Thank you!
