### ISSUE TITLE
The speed of The program

### ISSUE THREAD

**Issue by sunjunlishi** [TadasBaltrusaitis/CLM-framework#7]
1 one position could raise the speed.

CCNF_patch_expert::ComputeSigmas

if(sum_alphas > -0.000001 && sum_alphas < 0.000001)
	{
		int n_alphas = this->neurons.size();
		// sum the alphas first
		for(int a = 0; a < n_alphas; ++a)
		{
			sum_alphas += this->neurons[a].alpha;
		}
	}

'sum_alphas'  coumpute once and should be a static value.

thanks.
ou,my god.this place Only compute once,and it is not very significative。

2 another position to improve
void PDM::ComputeJacobian
	/*	X = shape_3D.at<float>(i,0);
		Y = shape_3D.at<float>(i+n,0);
		Z = shape_3D.at<float>(i+n*2,0);    */

	X =((float*)shape_3D.data)[shape_3D.cols*i];
		Y = ((float*)shape_3D.data)[shape_3D.cols*(i+n)];
		Z =((float*)shape_3D.data)[shape_3D.cols*(i+2*n)]  ;

**Comment by TadasBaltrusaitis** [comment]
Hi,

That is a valid way to speed things up, but I do not think it would have a major impact on performance while potentially sacrificing some readability. The biggest bottleneck at the moment is the template matching part of the code.

Thanks,
Tadas

**Comment by sunjunlishi** [comment]
oh,Yes.the speed is 140ms,and it is ok. The biggest bottleneck at the moment is the template matching part of the code.,Yes.  

the node patch,neither using meanshif, nor using probabilistic method; But using CCNF,Continuous Conditional Neural Fields. it is very good. hehe,thanks. and i have nothing to help you,please give my honour
