### ISSUE TITLE
one suggestion about Precision

### ISSUE THREAD

**Issue by sunjunlishi** [TadasBaltrusaitis/CLM-framework#9]
i have a little little suggestion  about precision;i can not  realize and do not know whether it is feasible。
Human faces have different degrees of side;Depending on the side, the training is different from the template, not the normalized, such as ASM, AAM。
How to deal with the input image, first with different side of the template, to make a preliminary judgment. Then select the side of the template, the deep level of the key points matching

**Comment by sunjunlishi** [comment]
Look forward to your comments.

**Comment by TadasBaltrusaitis** [comment]
Hi, If I understand your comment, you are suggesting a different model for different orientations of the face. This is actually already being done in the code, there are 7 models that are trained for the face for different orientations (ranging from -70 to 70 degrees profile), hence the model is able to cope with some extreme pose variations.

**Comment by sunjunlishi** [comment]
yes，thanks for your time
